const DATA_URL="./data/report.json";
const DEFAULT_TICKERS=["NVDA","TSLA","GOOGL","AMZN","AMD","MRVL","LRCX","PLTR","EQIX","DLR","SNDK","VRT","CEG","VST","SMR","TSM"];
const state={report:null,theme:"Tümü",tickers:loadTickers()};
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
function loadTickers(){try{const x=JSON.parse(localStorage.getItem("aiInfraWatchlist")||"null");return Array.isArray(x)&&x.length?x:[...DEFAULT_TICKERS]}catch{return[...DEFAULT_TICKERS]}}
function saveTickers(){localStorage.setItem("aiInfraWatchlist",JSON.stringify(state.tickers))}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c])}
function fmtDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Muscat"}).format(d)}
function fmtPct(v){if(v===null||v===undefined||Number.isNaN(Number(v)))return"—";const n=Number(v);return`${n>0?"+":""}${n.toFixed(1)}%`}
function pctClass(v){const n=Number(v);return Number.isFinite(n)&&n!==0?(n>0?"up":"down"):""}
function ratingInfo(r){return({STRONG_POSITIVE:["Güçlü Pozitif","positive"],POSITIVE:["Pozitif","positive"],NEUTRAL:["Nötr","neutral"],NEGATIVE:["Negatif","negative"],HIGH_UNCERTAINTY:["Yüksek Belirsizlik","warning"]})[r]||[r||"Nötr","neutral"]}
function cardClass(r){return["STRONG_POSITIVE","POSITIVE"].includes(r)?"positive":r==="NEGATIVE"?"negative":r==="HIGH_UNCERTAINTY"?"uncertain":""}
function confidence(c){const label={HIGH:"Yüksek Güven",MEDIUM:"Orta Güven",LOW:"Düşük Güven",UNVERIFIED:"Doğrulanmadı"}[c]||c;const cls=c==="HIGH"?"blue":c==="LOW"||c==="UNVERIFIED"?"warning":"neutral";return`<span class="badge ${cls}">${esc(label)}</span>`}
async function load(){$("#freshness").textContent="Yükleniyor";try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);state.report=await r.json();render()}catch(e){$("#freshness").textContent="Veri hatası";$("#freshness").className="badge negative";$("#events").innerHTML=`<article class="card negative"><h3>Bülten verisi açılamadı</h3><p>${esc(e.message)}</p></article>`}}
function render(){const d=state.report;const r=d.report,s=d.executive_summary,events=d.events||[];$("#generatedAt").textContent=fmtDate(r.generated_at);$("#eventCount").textContent=String(r.material_event_count??events.length);$("#dominantTheme").textContent=s.dominant_theme||"—";$("#mainRisk").textContent=s.main_risk||"—";$("#summaryTitle").textContent=s.headline||"Günlük görünüm";$("#summaryText").textContent=s.summary||"Önemli gelişme bulunmadı.";const age=Math.max(0,(Date.now()-new Date(r.generated_at).getTime())/36e5);$("#freshness").textContent=age<=30?"Güncel veri":"Veri eski olabilir";$("#freshness").className=`badge ${age<=30?"positive":"warning"}`;renderFilters(events);renderEvents(events);renderWatchlist(d.watchlist||[]);renderSources(events);renderChips()}
function renderFilters(events){const themes=["Tümü",...new Set(events.map(e=>e.primary_theme).filter(Boolean))];$("#filters").innerHTML=themes.map(t=>`<button class="filter ${state.theme===t?"active":""}" data-theme="${esc(t)}">${esc(t)}</button>`).join("");$$("#filters .filter").forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;renderFilters(events);renderEvents(events)})}
function renderEvents(events){const list=state.theme==="Tümü"?events:events.filter(e=>e.primary_theme===state.theme);$("#empty").classList.toggle("hidden",list.length>0);$("#events").innerHTML=list.map(e=>{const[rl,rc]=ratingInfo(e.research_view?.rating);const facts=(e.facts||[]).map(x=>`<li>${esc(x)}</li>`).join("");const risks=(e.research_view?.risks||[]).map(x=>`<li>${esc(x)}</li>`).join("");const src=e.sources?.[0];return`<article class="card ${cardClass(e.research_view?.rating)}"><div class="meta"><span>${esc(e.primary_theme)}</span><span>•</span><span>${esc(fmtDate(e.published_time))}</span></div><h3>${esc(e.headline)}</h3><div class="badges"><span class="badge ${rc}">${esc(rl)}</span>${confidence(e.confidence)}<span class="badge neutral">${esc(e.risk_badge||"STANDARD")}</span></div><div class="section"><strong>NE OLDU?</strong><ul>${facts}</ul></div><div class="section"><strong>NEDEN ÖNEMLİ?</strong><p>${esc(e.why_it_matters)}</p></div><div class="section"><strong>YATIRIM AÇISINDAN ANLAMI</strong><p>${esc(e.investment_meaning||e.research_view?.summary||"")}</p>${risks?`<ul>${risks}</ul>`:""}</div>${src?`<a class="source-link" href="${esc(src.url)}" target="_blank" rel="noopener noreferrer">Kaynağı aç ↗</a>`:""}</article>`}).join("")}
function renderWatchlist(items){const map=new Map(items.map(x=>[x.ticker,x]));$("#watchlistBody").innerHTML=state.tickers.map(t=>{const x=map.get(t)||{ticker:t,company:t,risk_badge:"VERİ BEKLENİYOR"};return`<tr><td><div class="ticker-name"><strong>${esc(x.ticker)}</strong><span>${esc(x.company||"")}</span></div></td><td>${x.price==null?"—":`${esc(x.currency||"USD")} ${Number(x.price).toFixed(2)}`}</td><td class="${pctClass(x.return_1d_pct)}">${fmtPct(x.return_1d_pct)}</td><td class="${pctClass(x.return_21d_pct)}">${fmtPct(x.return_21d_pct)}</td><td class="${pctClass(x.return_252d_pct)}">${fmtPct(x.return_252d_pct)}</td><td class="${pctClass(x.distance_from_52w_high_pct)}">${fmtPct(x.distance_from_52w_high_pct)}</td><td><span class="badge ${x.risk_badge==="SPECULATIVE"?"warning":"neutral"}">${esc(x.risk_badge||"STANDARD")}</span></td></tr>`}).join("")}
function renderSources(events){const out=[];events.forEach(e=>(e.sources||[]).forEach(s=>out.push({...s,event:e.headline})));$("#sourcesList").innerHTML=out.length?out.map(s=>`<article class="source"><div class="meta"><span>${esc(s.source_type||"SECONDARY")}</span><span>•</span><span>${esc(s.publisher||"")}</span><span>•</span><span>${esc(fmtDate(s.published_at))}</span></div><h3>${esc(s.title)}</h3><p>${esc(s.event)}</p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">Kaynağı aç ↗</a></article>`).join(""):`<div class="empty"><h3>Kaynak bulunamadı</h3></div>`}
function renderChips(){$("#tickerChips").innerHTML=state.tickers.map(t=>`<span class="chip">${esc(t)} <button data-remove="${esc(t)}" aria-label="${esc(t)} kaldır">×</button></span>`).join("");$$('[data-remove]').forEach(b=>b.onclick=()=>{state.tickers=state.tickers.filter(t=>t!==b.dataset.remove);saveTickers();renderChips();renderWatchlist(state.report?.watchlist||[])})}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===t));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${t.dataset.view}View`).classList.add('active')});
$("#refresh").onclick=load;$("#tickerForm").onsubmit=e=>{e.preventDefault();const t=$("#ticker").value.trim().toUpperCase().replace(/[^A-Z.-]/g,"");if(t&&!state.tickers.includes(t)){state.tickers.push(t);saveTickers();renderChips();renderWatchlist(state.report?.watchlist||[])}$("#ticker").value=""};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
load();
